/**
 * Created by 00 on 14-4-28.
 */
var BacteriaType = [
    {
        type:0,
        textureName:"bacteriaYellow1.png",
        //bulletType:"W2.png",
        HP:100,
        moveSpeed:5,
        moveType:PvZ.BACTERIA_MOVE_TYPE.HORIZONTAL_WALK,
        attackPower:1,
        attackMode:PvZ.BACTERIA_ATTACK_TYPE.INFECT
    },
    {
        type:1,
        moveSpeed:10,
        textureName:"Germ.png",
        //bulletType:"W2.png",
        HP:200,
        moveType:PvZ.BACTERIA_MOVE_TYPE.HORIZONTAL_WALK,
        attackPower:2,
        attackMode:PvZ.BACTERIA_ATTACK_TYPE.INFECT
    },
    {
        type:7,
        moveSpeed:5,
        textureName:"Virus.png",
        //bulletType:"W2.png",
        HP:200,
        moveType:PvZ.BACTERIA_MOVE_TYPE.HORIZONTAL_WALK,
        attackPower:3,
        attackMode:PvZ.BACTERIA_ATTACK_TYPE.INFECT
    },
    {
        type:3,
        moveSpeed:10,
        //textureName:"E1.png",
        //bulletType:"W2.png",
        HP:200,
        moveType:PvZ.BACTERIA_MOVE_TYPE.HORIZONTAL_WALK,
        attackPower:4,
        attackMode:PvZ.BACTERIA_ATTACK_TYPE.INFECT
    },
    {
        type:4,
        moveSpeed:10,
        //textureName:"E1.png",
        //bulletType:"W2.png",
        HP:200,
        moveType:PvZ.BACTERIA_MOVE_TYPE.HORIZONTAL_WALK,
        attackPower:5,
        attackMode:PvZ.BACTERIA_ATTACK_TYPE.INFECT
    }
]
