/**
 * Created by 00 on 14-4-28.
 */
var BacteriaType = [
    {
        type:0,
        textureName:"bacteriaGreen",
        HP:800,
        moveSpeed:50,
        moveType:PvZ.BACTERIA_MOVE_TYPE.HORIZONTAL_WALK,
        attackPower:3,
        attackMode:PvZ.BACTERIA_ATTACK_TYPE.INFECT
    },
    {
        type:1,
        moveSpeed:30,
        textureName:"bacteriaPink",
        HP:500,
        moveType:PvZ.BACTERIA_MOVE_TYPE.HORIZONTAL_WALK,
        attackPower:2,
        attackMode:PvZ.BACTERIA_ATTACK_TYPE.INFECT
    },
    {
        type:2,
        moveSpeed:20,
        textureName:"bacteriaPurple",
        HP:250,
        moveType:PvZ.BACTERIA_MOVE_TYPE.HORIZONTAL_WALK,
        attackPower:1,
        attackMode:PvZ.BACTERIA_ATTACK_TYPE.INFECT
    }
]
