/**
 * Created by 00 on 14-4-28.
 */
var BacteriaType = [
    {
        type:0,
        textureName:"bacteriaGreen",
        //bulletType:"W2.png",
        HP:100,
        moveSpeed:50,
        moveType:PvZ.BACTERIA_MOVE_TYPE.HORIZONTAL_WALK,
        attackPower:1,
        attackMode:PvZ.BACTERIA_ATTACK_TYPE.INFECT
    },
    {
        type:1,
        moveSpeed:25,
        textureName:"bacteriaPink",
        //bulletType:"W2.png",
        HP:200,
        moveType:PvZ.BACTERIA_MOVE_TYPE.HORIZONTAL_WALK,
        attackPower:2,
        attackMode:PvZ.BACTERIA_ATTACK_TYPE.INFECT
    },
    {
        type:2,
        moveSpeed:75,
        textureName:"bacteriaPurple",
        //bulletType:"W2.png",
        HP:200,
        moveType:PvZ.BACTERIA_MOVE_TYPE.HORIZONTAL_WALK,
        attackPower:3,
        attackMode:PvZ.BACTERIA_ATTACK_TYPE.INFECT
    }
]
