/**
 * Created by 00 on 14-4-10.
 */
var Level1 = {
    bacteriaMax:6,
    bacterias:[
        {
            ShowType:"Repeat",
            ShowTime:"00:10",
            Lane:1,
            Type:0
        },
        {
            ShowType:"Repeat",
            ShowTime:"00:15",
            Lane:2,
            Type:1
        },
        {
            ShowType:"Repeat",
            ShowTime:"00:06",
            Lane:3,
            Type:2
        },
        {
            ShowType:"Repeat",
            ShowTime:"00:08",
            Lane:4,
            Type:0
        },
        {
            ShowType:"Repeat",
            ShowTime:"00:10",
            Lane:1,
            Type:1
        },
        {
            ShowType:"Repeat",
            ShowTime:"00:15",
            Lane:5,
            Type:0
        },
        {
            ShowType:"Repeat",
            ShowTime:"00:05",
            Lane:3,
            Type:2
        }
    ]
};
